import { useEffect, useMemo, useState } from 'react'
import {
  Activity, ArrowRight, Bell, BellRing, BrainCircuit, CalendarDays, Check,
  ChevronRight, Clock3, LayoutDashboard, LineChart, Menu, MessageCircle,
  Minus, Pause, Play, RefreshCw, ShieldCheck, Sparkles, Stethoscope,
  TrendingUp, UserRound, Users, X, Zap,
} from 'lucide-react'
import { explainPrediction, getHospitalAvailability, predictWait } from './api'

const baseQueue = [
  { token: 'A117', patient: 'Patient 1', status: 'Consulting', wait: '—' },
  { token: 'A118', patient: 'Patient 2', status: 'Waiting', wait: '5 min' },
  { token: 'A119', patient: 'Patient 3', status: 'Waiting', wait: '9 min' },
  { token: 'A120', patient: 'Patient 4', status: 'Waiting', wait: '14 min' },
  { token: 'A121', patient: 'Patient 5', status: 'Waiting', wait: '18 min' },
  { token: 'A122', patient: 'Patient 6', status: 'Waiting', wait: '23 min' },
  { token: 'A123', patient: 'Patient 7', status: 'Waiting', wait: '27 min' },
  { token: 'A124', patient: 'Patient 8', status: 'Waiting', wait: '31 min' },
  { token: 'A128', patient: 'Rahul Sharma', status: 'Your token', wait: '32 min' },
]

const navItems = [
  { id: 'home', label: 'Home', icon: LayoutDashboard },
  { id: 'patient', label: 'Patient', icon: UserRound },
  { id: 'queue', label: 'Live Queue', icon: Activity },
  { id: 'prediction', label: 'Prediction', icon: BrainCircuit },
  { id: 'notifications', label: 'Notifications', icon: Bell },
  { id: 'assistant', label: 'AI Assistant', icon: Sparkles },
  { id: 'analytics', label: 'Analytics', icon: LineChart },
]

const hospitals = [
  { id: 'citycare', name: 'CityCare Hospital', city: 'Pune' },
  { id: 'apollo', name: 'Apollo Care Centre', city: 'Mumbai' },
  { id: 'fortis', name: 'Fortis Wellness Hospital', city: 'Bengaluru' },
  { id: 'manipal', name: 'Manipal Health Point', city: 'Hyderabad' },
]

const translations = {
  en: {
    language: 'Language', home: 'Home', patient: 'Patient', queue: 'Live Queue', prediction: 'Prediction', notifications: 'Notifications', assistant: 'AI Assistant', analytics: 'Analytics',
    hospital: 'CityCare Hospital', heroEyebrow: 'SMART OPD FLOW · CITYCARE HOSPITAL', heroTitle: 'Your health,', heroTitleAccent: 'smarter.', heroDescription: 'AI-powered healthcare assistance for faster, simpler and more personalized health information, starting with a calmer OPD visit.', getStarted: 'Get started', explore: 'Explore services', trusted: 'Trusted for calmer hospital visits', featureEyebrow: 'ONE CLEAR VIEW', featureTitle: 'Healthcare support, thoughtfully connected.', featureDescription: 'Simple tools for patients, doctors and care teams, all in one clear experience.', why: 'Why QureAI?', footer: 'Making hospital queues predictable, transparent and patient-friendly.',
  },
  hi: {
    language: 'भाषा', home: 'होम', patient: 'मरीज़', queue: 'लाइव कतार', prediction: 'अनुमान', notifications: 'सूचनाएँ', assistant: 'AI सहायक', analytics: 'विश्लेषण',
    hospital: 'सिटीकेयर अस्पताल', heroEyebrow: 'स्मार्ट ओपीडी · सिटीकेयर अस्पताल', heroTitle: 'आपका स्वास्थ्य,', heroTitleAccent: 'और स्मार्ट।', heroDescription: 'तेज़, आसान और आपकी ज़रूरत के अनुसार स्वास्थ्य जानकारी के लिए AI सहायता, एक शांत OPD अनुभव से शुरुआत।', getStarted: 'शुरू करें', explore: 'सेवाएँ देखें', trusted: 'शांत अस्पताल अनुभव के लिए', featureEyebrow: 'एक स्पष्ट दृश्य', featureTitle: 'स्वास्थ्य सहायता, एक साथ और सरल।', featureDescription: 'मरीज़ों, डॉक्टरों और देखभाल टीमों के लिए सरल और उपयोगी उपकरण।', why: 'QureAI क्यों?', footer: 'अस्पताल की कतारों को अनुमानित, पारदर्शी और मरीज़ों के अनुकूल बनाना।',
  },
  mr: {
    language: 'भाषा', home: 'मुख्यपृष्ठ', patient: 'रुग्ण', queue: 'थेट रांग', prediction: 'अंदाज', notifications: 'सूचना', assistant: 'AI सहाय्यक', analytics: 'विश्लेषण',
    hospital: 'सिटीकेअर रुग्णालय', heroEyebrow: 'स्मार्ट ओपीडी · सिटीकेअर रुग्णालय', heroTitle: 'तुमचे आरोग्य,', heroTitleAccent: 'अधिक स्मार्ट.', heroDescription: 'जलद, सोपी आणि वैयक्तिक आरोग्य माहितीसाठी AI सहाय्य, अधिक शांत OPD अनुभवापासून सुरुवात.', getStarted: 'सुरुवात करा', explore: 'सेवा पहा', trusted: 'अधिक शांत रुग्णालयीन अनुभवासाठी', featureEyebrow: 'एक स्पष्ट दृश्य', featureTitle: 'आरोग्य सहाय्य, एकाच ठिकाणी.', featureDescription: 'रुग्ण, डॉक्टर आणि काळजी घेणाऱ्या टीमसाठी सोपी साधने.', why: 'QureAI का?', footer: 'रुग्णालयातील रांगा अंदाजे, पारदर्शक आणि रुग्णांसाठी सोप्या बनवणे.',
  },
}

function formatToken(number) { return `A${String(number).padStart(3, '0')}` }
function estimateWait(ahead, speed = 1) { return Math.max(4, Math.round(ahead * 4.2 * speed * 0.65)) }
function fallbackAvailability(hospital) { return { hospital_id: hospital.id, load: hospital.id === 'apollo' ? 'Busy' : 'Normal', next_slot: hospital.id === 'manipal' ? '9:50 AM' : '10:30 AM', doctors_available: hospital.id === 'apollo' ? 6 : 4, departments: ['General Medicine', 'Cardiology', 'Pediatrics'], updated: 'just now', prototype_data: true } }

export default function App() {
  const [page, setPage] = useState(() => localStorage.getItem('opd-page') || 'home')
  const [language, setLanguage] = useState(() => localStorage.getItem('opd-language') || 'en')
  const [hospitalId, setHospitalId] = useState(() => localStorage.getItem('opd-hospital') || 'citycare')
  const [menuOpen, setMenuOpen] = useState(false)
  const [queue, setQueue] = useState(() => {
    const saved = localStorage.getItem('opd-queue')
    return saved ? JSON.parse(saved) : { current: 117, user: 128, speed: 1, lastUpdated: '30 seconds ago', paused: false }
  })
  const [notifications, setNotifications] = useState(true)
  const [showToken, setShowToken] = useState(Boolean(localStorage.getItem('opd-token')))
  const [aiWait, setAiWait] = useState(null)
  const [availability, setAvailability] = useState(null)

  useEffect(() => { localStorage.setItem('opd-page', page) }, [page])
  useEffect(() => { localStorage.setItem('opd-language', language); document.documentElement.lang = language }, [language])
  useEffect(() => { localStorage.setItem('opd-hospital', hospitalId) }, [hospitalId])
  useEffect(() => { localStorage.setItem('opd-queue', JSON.stringify(queue)) }, [queue])

  const ahead = Math.max(0, queue.user - queue.current - 1)
  const navigate = (next) => { setPage(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const moveQueue = (amount = 1) => setQueue((state) => ({ ...state, current: Math.min(state.user - 1, state.current + amount), speed: 0.92 + Math.random() * 0.16, lastUpdated: 'just now' }))
  const refreshQueue = () => moveQueue(1)
  const generateToken = () => { localStorage.setItem('opd-token', 'A128'); setShowToken(true); navigate('patient') }
  const t = translations[language]
  const hospital = hospitals.find((item) => item.id === hospitalId) || hospitals[0]
  const translatedNav = navItems.map((item) => ({ ...item, label: t[item.id] }))

  useEffect(() => {
    let active = true
    const loadAIData = async () => {
      const predictionPayload = { patients_ahead: ahead, average_consultation_minutes: 4.2, doctor_available: true, queue_movement: queue.speed, queue_speed: queue.speed < .98 ? 'fast' : queue.speed > 1.04 ? 'busy' : 'normal', opd_load: queue.speed > 1.04 ? 'high' : 'normal' }
      const [predictionResult, availabilityResult] = await Promise.allSettled([predictWait(predictionPayload), getHospitalAvailability(hospital.id)])
      if (!active) return
      setAiWait(predictionResult.status === 'fulfilled' ? predictionResult.value.estimated_wait_minutes : null)
      setAvailability(availabilityResult.status === 'fulfilled' ? availabilityResult.value : fallbackAvailability(hospital))
    }
    loadAIData()
    return () => { active = false }
  }, [ahead, hospital.id, queue.speed])

  const wait = aiWait || estimateWait(ahead, queue.speed)

  return <div className="app-shell">
    <header className="topbar">
      <button className="brand" onClick={() => navigate('home')} aria-label="Go to home"><span className="brand-mark"><Activity size={19} strokeWidth={2.7} /></span><span><b>QureAI</b></span></button>
      <nav className={`main-nav ${menuOpen ? 'open' : ''}`}>
        {translatedNav.map(({ id, label, icon: Icon }) => <button key={id} className={page === id ? 'active' : ''} onClick={() => navigate(id)}><Icon size={16} />{label}</button>)}
      </nav>
      <div className="top-actions"><label className="hospital-picker"><span className="status-dot" /><select value={hospitalId} onChange={(event) => setHospitalId(event.target.value)} aria-label="Select hospital">{hospitals.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.city}</option>)}</select></label><label className="language-picker"><span>{t.language}</span><select value={language} onChange={(event) => setLanguage(event.target.value)} aria-label={t.language}><option value="en">English</option><option value="hi">हिन्दी</option><option value="mr">मराठी</option></select></label><button className="icon-button notification-button" onClick={() => navigate('notifications')} aria-label={t.notifications}><Bell size={18} /><span /></button><button className="avatar" onClick={() => navigate('patient')}>RS</button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></div>
    </header>
    <main>
      {page === 'home' && <HomePage navigate={navigate} wait={wait} ahead={ahead} t={t} hospital={hospital} availability={availability} aiPowered={Boolean(aiWait)} />}
      {page === 'patient' && <PatientPage showToken={showToken} generateToken={generateToken} navigate={navigate} wait={wait} ahead={ahead} />}
      {page === 'queue' && <QueuePage queue={queue} ahead={ahead} wait={wait} refreshQueue={refreshQueue} navigate={navigate} />}
      {page === 'prediction' && <PredictionPage ahead={ahead} wait={wait} />}
      {page === 'notifications' && <NotificationPage ahead={ahead} wait={wait} navigate={navigate} notifications={notifications} setNotifications={setNotifications} />}
      {page === 'assistant' && <AIAssistantPage ahead={ahead} wait={wait} hospital={hospital} availability={availability} />}
      {page === 'analytics' && <AnalyticsPage />}
    </main>
    <footer><div className="footer-inner"><div className="brand footer-brand"><span className="brand-mark"><Activity size={17} /></span><span><b>QureAI</b></span></div><p>{t.footer}</p><span className="footer-note">Prototype · Health Tech · Hackathon 2026</span></div></footer>
  </div>
}

function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div> }
function Button({ children, onClick, variant = 'primary', icon: Icon, type = 'button' }) { return <button type={type} className={`button ${variant}`} onClick={onClick}>{Icon && <Icon size={17} />}{children}</button> }
function StatusBadge({ children = 'Normal', type = 'normal' }) { return <span className={`status-badge ${type}`}><span />{children}</span> }
function StatCard({ icon: Icon, label, value, detail, color = 'blue' }) { return <div className="stat-card"><div className={`stat-icon ${color}`}><Icon size={18} /></div><div><span className="stat-label">{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div></div> }

function HomePage({ navigate, wait, ahead, t, hospital, availability, aiPowered }) {
  return <>
    <section className="hero page-container"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-pulse" />{t.heroEyebrow}</div><h1>{t.heroTitle}<br /><em>{t.heroTitleAccent}</em></h1><p className="hero-lede">{t.heroDescription}</p><div className="hero-actions"><Button onClick={() => navigate('patient')} icon={ArrowRight}>{t.getStarted}</Button><Button onClick={() => navigate('queue')} variant="secondary" icon={Activity}>{t.explore}</Button></div><div className="trust-row"><div className="trust-avatars"><span>AS</span><span>PM</span><span>RK</span><span>+</span></div><span>{t.trusted}</span></div><div className="hero-hospital-context"><span className="status-dot" /> Viewing queue at <b>{hospital.name}</b>, {hospital.city}</div><div className="availability-card"><div className="availability-icon"><CalendarDays size={17} /></div><div><b>Checkup availability</b><span>{availability?.doctors_available || '—'} doctors available · Next slot {availability?.next_slot || 'loading...'}</span></div><StatusBadge>{availability?.load || 'Checking'}</StatusBadge><small className="ai-label"><BrainCircuit size={12} /> AI queue signal {aiPowered ? 'active' : 'demo mode'}</small></div></div><div className="hero-visual"><div className="hero-image-wrap"><img src="https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=720&q=85" alt="Doctor ready for a patient consultation" /><div className="hero-image-glow" /></div><div className="medical-float float-top"><span className="float-icon blue">♥</span><span><b>Health monitoring</b><small>Vitals look steady</small></span><i>●</i></div><div className="medical-float float-bottom"><span className="float-icon green">✓</span><span><b>Doctor consultation</b><small>Care, made simpler</small></span></div><div className="hero-queue-preview"><QueuePreview wait={wait} ahead={ahead} /></div></div></section>
    <section className="page-container feature-section"><div className="section-heading"><div><div className="eyebrow">{t.featureEyebrow}</div><h2>{t.featureTitle}</h2></div><p>{t.featureDescription}</p></div><div className="feature-grid"><FeatureCard icon={BrainCircuit} title="AI diagnostics" text="Turn complex healthcare information into a clearer next step." accent="lavender" /><FeatureCard icon={Activity} title="Health monitoring" text="Stay close to the signals that matter during your care journey." accent="mint" /><FeatureCard icon={BellRing} title="Doctor consultation" text="Know when your turn is near and spend less time waiting." accent="peach" /><FeatureCard icon={Clock3} title="Medication information" text="Keep important treatment information easy to find and understand." accent="lavender" /><FeatureCard icon={TrendingUp} title="Health analytics" text="See patterns in your visits and make more informed plans." accent="mint" /><FeatureCard icon={Stethoscope} title="Hospital locator" text="Find the right department and the right care, faster." accent="peach" /></div></section>
    <section className="why-section"><div className="page-container"><div className="section-heading"><div><div className="eyebrow">THE DIFFERENCE</div><h2>{t.why}</h2></div><p>Traditional token systems tell you a number. We give that number context.</p></div><div className="comparison-grid"><div className="comparison-card traditional"><span className="comparison-label">TRADITIONAL TOKEN SYSTEM</span><h3>“You are Token A128.”</h3><ul><li><X size={16} />Only token number</li><li><X size={16} />No waiting-time estimate</li><li><X size={16} />No live queue visibility</li></ul></div><div className="comparison-card smart"><span className="comparison-label">QUREAI</span><h3>“You are A128. 11 patients ahead. About 32 minutes.”</h3><ul><li><Check size={16} />Estimated waiting time</li><li><Check size={16} />Live queue movement</li><li><Check size={16} />Historical consultation analysis</li><li><Check size={16} />Patient notifications</li><li><Check size={16} />Care-team workspace</li></ul></div></div></div></section>
    <section className="how-section page-container"><div className="section-heading"><div><div className="eyebrow">A CALMER VISIT</div><h2>How it works</h2></div></div><div className="steps"><Step number="01" title="Get token" text="Check in and receive your digital OPD token." /><Step number="02" title="Track queue" text="See your place and the current token live." /><Step number="03" title="AI estimates wait" text="A useful estimate adapts to queue speed." /><Step number="04" title="Get notified" text="Receive a nudge when your turn approaches." /></div></section>
  </>
}
function QueuePreview({ wait, ahead }) { return <div className="dashboard-preview"><div className="preview-top"><span className="window-dot red" /><span className="window-dot yellow" /><span className="window-dot green" /><span className="preview-title">Patient view <span>● Live</span></span></div><div className="preview-content"><div className="mini-greeting"><div><span className="muted">Good morning, Rahul</span><h3>Your OPD journey</h3></div><span className="mini-avatar">RS</span></div><div className="token-card"><div><span>Your token</span><strong>A128</strong></div><div className="token-wait"><span>Estimated wait</span><strong>{wait} <small>min</small></strong></div></div><div className="mini-stats"><div><span>Patients ahead</span><b>{ahead}</b></div><div><span>Current token</span><b>A117</b></div><div><span>Queue status</span><b className="green-text">Moving normally</b></div></div><div className="queue-line"><div className="line-label"><span>Queue progress</span><b>64%</b></div><div className="progress"><span style={{ width: '64%' }} /></div><div className="line-foot"><span>A117 now consulting</span><span>Your turn · A128</span></div></div></div></div> }
function FeatureCard({ icon: Icon, title, text, accent }) { return <div className="feature-card"><div className={`feature-icon ${accent}`}><Icon size={21} /></div><h3>{title}</h3><p>{text}</p><span className="feature-arrow"><ArrowRight size={16} /></span></div> }
function Step({ number, title, text }) { return <div className="step"><span className="step-number">{number}</span><div className="step-line" /><h3>{title}</h3><p>{text}</p></div> }

function PatientPage({ showToken, generateToken, navigate, wait, ahead }) {
  const [form, setForm] = useState({ name: 'Rahul Sharma', age: '32', department: 'General Medicine', doctor: 'Dr. Ananya Sharma', opd: 'Morning OPD' })
  if (showToken) return <div className="page-container inner-page"><PageHeader eyebrow="PATIENT CHECK-IN" title="Your token is ready." description="Keep this screen handy. Your queue position will update as the OPD moves." action={<StatusBadge>Queue active</StatusBadge>} /><div className="token-layout"><div className="patient-token-card"><div className="token-card-head"><span className="eyebrow">GENERAL MEDICINE · MORNING OPD</span><span className="token-live"><span /> Live</span></div><div className="big-token"><span>YOUR TOKEN</span><strong>A128</strong></div><div className="token-details"><div><span>Doctor</span><b>Dr. Ananya Sharma</b></div><div><span>Department</span><b>General Medicine</b></div></div><div className="token-prediction"><div><Clock3 size={19} /><span>Estimated waiting time</span><strong>{wait} min</strong></div><div><Users size={19} /><span>Patients ahead</span><strong>{ahead}</strong></div></div><div className="status-row"><StatusBadge /> <span>Queue is moving normally</span></div><div className="token-actions"><Button onClick={() => navigate('queue')} icon={Activity}>View live queue</Button><Button onClick={() => {}} variant="secondary" icon={Bell}>Enable notifications</Button></div></div><div className="next-steps"><div className="eyebrow">WHAT HAPPENS NEXT</div><h3>We’ll keep you in the loop.</h3><div className="tiny-timeline"><TimelineItem icon={Check} title="Token generated" text="Just now" done /><TimelineItem icon={Activity} title="Queue started" text="Currently active" done /><TimelineItem icon={Bell} title="Your turn approaching" text="We’ll notify you" /><TimelineItem icon={Stethoscope} title="Consultation" text="At the doctor’s room" /></div><div className="prototype-note"><ShieldCheck size={16} /><span>Prototype estimate based on mock queue data. Not medically validated.</span></div></div></div></div>
  return <div className="page-container inner-page"><PageHeader eyebrow="PATIENT CHECK-IN" title="Start your OPD visit." description="Enter a few details and we’ll create a live demo token for your visit." /><div className="form-layout"><form className="checkin-form" onSubmit={(event) => { event.preventDefault(); generateToken() }}><div className="form-header"><div className="feature-icon lavender"><UserRound size={20} /></div><div><h3>Patient details</h3><p>All fields are for this prototype demo.</p></div></div><div className="form-grid"><label>Patient name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Age<input type="number" value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} required /></label><label>Department<select value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })}><option>General Medicine</option><option>Cardiology</option><option>Orthopedics</option><option>Pediatrics</option></select></label><label>Doctor<select value={form.doctor} onChange={(e) => setForm({ ...form, doctor: e.target.value })}><option>Dr. Ananya Sharma</option><option>Dr. Vikram Mehta</option><option>Dr. Priya Nair</option></select></label><label className="full">Preferred OPD<select value={form.opd} onChange={(e) => setForm({ ...form, opd: e.target.value })}><option>Morning OPD · 08:00 - 13:00</option><option>Afternoon OPD · 14:00 - 18:00</option></select></label></div><Button type="submit" icon={ArrowRight}>Generate token</Button><small className="form-disclaimer"><ShieldCheck size={14} /> Demo data only · No account or authentication needed</small></form><div className="form-aside"><div className="aside-glow" /><CalendarDays size={27} /><h3>Today at CityCare</h3><p>General Medicine is moving normally. The average consultation is <b>4.2 minutes</b>.</p><div className="aside-stat"><span>Currently consulting</span><strong>A117</strong></div><div className="aside-stat"><span>Expected wait for new token</span><strong>~32 min</strong></div></div></div></div>
}
function TimelineItem({ icon: Icon, title, text, done }) { return <div className={`timeline-item ${done ? 'done' : ''}`}><div className="timeline-icon"><Icon size={15} /></div><div><b>{title}</b><span>{text}</span></div></div> }

function QueuePage({ queue, ahead, wait, refreshQueue, navigate }) { const queueItems = baseQueue.map((item) => item.token === 'A117' ? { ...item, token: formatToken(queue.current) } : item); return <div className="page-container inner-page"><PageHeader eyebrow="LIVE QUEUE · GENERAL MEDICINE" title="See the queue move." description="A live view of today’s OPD queue at CityCare Multispeciality Hospital." action={<Button onClick={refreshQueue} variant="secondary" icon={RefreshCw}>Refresh queue</Button>} /><div className="queue-summary"><div className="current-token"><span>Current token</span><strong>{formatToken(queue.current)}</strong><StatusBadge /></div><div><span>Your token</span><strong>A128</strong></div><div><span>Patients ahead</span><strong>{ahead}</strong></div><div><span>Estimated wait</span><strong>{wait} <small>min</small></strong></div></div><div className="updated-line"><span className="live-indicator" /> Last updated {queue.lastUpdated}<span className="update-separator" /> <span>Queue speed: {queue.speed < 0.98 ? 'Faster than usual' : queue.speed > 1.04 ? 'A little busy' : 'Normal'}</span></div><div className="queue-board"><div className="board-header"><div><div className="eyebrow">TODAY’S PATIENTS</div><h2>General Medicine queue</h2></div><span className="board-date">Monday, 19 September 2026</span></div><div className="queue-list">{queueItems.map((item) => <div className={`queue-row ${item.token === 'A128' ? 'user-row' : ''} ${item.status === 'Consulting' ? 'consulting-row' : ''}`} key={item.token}><span className="row-token">{item.token}</span><span className="row-patient">{item.token === 'A128' ? 'Rahul Sharma' : item.patient}</span><span className={`row-status ${item.status === 'Consulting' ? 'consulting' : ''}`}>{item.status}</span><span className="row-wait">{item.token === 'A128' ? `${wait} min` : item.wait}</span>{item.token === 'A128' && <span className="you-pill">YOU</span>}</div>)}</div><div className="board-foot"><span><Users size={15} /> 20 patients in queue today</span><Button onClick={() => navigate('prediction')} variant="text" icon={ChevronRight}>How is this estimated?</Button></div></div></div> }

function PredictionPage({ ahead, wait }) { return <div className="page-container inner-page"><PageHeader eyebrow="PREDICTIVE INSIGHT" title="AI waiting-time prediction" description="A transparent estimate that adapts as your OPD queue moves." action={<span className="prototype-tag"><Sparkles size={14} /> Prototype model</span>} /><div className="prediction-layout"><div className="prediction-main"><div className="estimate-card"><div className="estimate-top"><span>ESTIMATED WAIT</span><span className="confidence"><span /> Live estimate</span></div><div className="estimate-value">{wait}<small>minutes</small></div><div className="estimate-range"><span>Likely range</span><b>{Math.max(4, wait - 4)} – {wait + 5} min</b></div><div className="estimate-progress"><div className="estimate-progress-track"><span style={{ width: `${Math.min(90, 100 - ahead * 2)}%` }} /></div><div><span>Queue position</span><b>{ahead} patients ahead</b></div></div></div><div className="factors-card"><div className="card-title"><div><div className="eyebrow">THE SIGNALS BEHIND IT</div><h2>Prediction factors</h2></div><BrainCircuit size={22} /></div><Factor label="Patients ahead" value={`${ahead} patients`} percent={Math.min(88, ahead * 6)} /><Factor label="Average consultation time" value="4.2 min" percent={57} /><Factor label="Current queue speed" value="Normal" percent={64} /><Factor label="Historical consultation pattern" value="Normal" percent={48} /></div></div><div className="prediction-aside"><div className="formula-card"><div className="eyebrow">HOW IT WORKS</div><h3>A useful estimate, built from real signals.</h3><div className="formula"><span>{ahead} patients</span><Minus size={15} /><span>4.2 min avg.</span><ArrowRight size={16} /><b>{ahead * 4.2 > 0 ? Math.round(ahead * 4.2) : 0} min</b></div><p>We then adjust this base with queue speed, historical consultation duration and current OPD load.</p></div><div className="chart-card"><div className="card-title"><div><div className="eyebrow">RECENT CONSULTATIONS</div><h3>Duration trend</h3></div><TrendingUp size={19} /></div><MiniChart /><div className="chart-labels"><span>A117</span><span>A118</span><span>A119</span><span>A120</span><span>A121</span><span>A122</span></div></div><div className="prototype-note"><ShieldCheck size={16} /><span>Prototype estimation only. This is not medically validated and should not be used for urgent decisions.</span></div></div></div></div> }
function Factor({ label, value, percent }) { return <div className="factor"><div><span>{label}</span><b>{value}</b></div><div className="factor-bar"><span style={{ width: `${percent}%` }} /></div></div> }
function MiniChart() { return <div className="mini-chart"><svg viewBox="0 0 420 110" preserveAspectRatio="none"><path d="M0 79 C30 75, 45 38, 72 52 S118 77, 140 52 S188 27, 212 45 S250 75, 278 58 S314 36, 340 45 S380 76, 420 21" fill="none" stroke="#4665e8" strokeWidth="3" /><path d="M0 79 C30 75, 45 38, 72 52 S118 77, 140 52 S188 27, 212 45 S250 75, 278 58 S314 36, 340 45 S380 76, 420 21 V110 H0Z" fill="url(#chartFill)" opacity=".25" /><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#6c7ff2" /><stop offset="1" stopColor="#fff" stopOpacity="0" /></linearGradient></defs></svg></div> }

function AIAssistantPage({ ahead, wait, hospital, availability }) {
  const [question, setQuestion] = useState('Why is my estimated wait about this long?')
  const [answer, setAnswer] = useState('')
  const [loading, setLoading] = useState(false)
  const askAssistant = async (event) => {
    event?.preventDefault()
    setLoading(true)
    const payload = { patients_ahead: ahead, average_consultation_minutes: 4.2, doctor_available: true, queue_movement: 1, queue_speed: 'normal', opd_load: availability?.load === 'Busy' ? 'high' : 'normal' }
    try {
      const result = await explainPrediction(payload)
      setAnswer(`${result.text} ${question.toLowerCase().includes('hospital') ? `${hospital.name} currently has ${availability?.doctors_available || 0} doctors available, with the next checkup slot at ${availability?.next_slot || 'the next available time'}.` : ''}`)
    } catch {
      setAnswer(`You have ${ahead} patients ahead and the current estimate is about ${wait} minutes. The estimate uses queue position, a 4.2-minute average consultation, and current queue movement. ${hospital.name} has ${availability?.doctors_available || 0} doctors available today. This is a prototype estimate, not medical advice.`)
    } finally { setLoading(false) }
  }
  return <div className="page-container inner-page"><PageHeader eyebrow="QUREAI TOOL" title="Ask QureAI." description="Get a simple explanation of your queue, hospital availability, and next step." action={<span className="prototype-tag"><Sparkles size={14} /> AI assistant</span>} /><div className="assistant-layout"><div className="assistant-card"><div className="assistant-orb"><Sparkles size={23} /></div><div className="assistant-intro"><h2>Your OPD companion</h2><p>Ask about your estimated wait or today’s hospital availability. QureAI uses live demo queue signals to keep the answer grounded.</p></div><div className="suggested-prompts"><button onClick={() => setQuestion('Why is my estimated wait about this long?')}>Why is my wait this long?</button><button onClick={() => setQuestion('What is available at this hospital today?')}>What is available today?</button><button onClick={() => setQuestion('When should I return near my turn?')}>When should I return?</button></div><form className="assistant-form" onSubmit={askAssistant}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} aria-label="Ask QureAI a question" rows="3" /><button className="button primary" type="submit" disabled={loading}>{loading ? 'Thinking...' : 'Ask QureAI'} <ArrowRight size={17} /></button></form>{answer && <div className="assistant-answer"><div className="answer-heading"><span><Sparkles size={15} /> QureAI response</span><span className="answer-live">Prototype AI</span></div><p>{answer}</p></div>}</div><div className="assistant-context"><div className="eyebrow">CURRENT CONTEXT</div><h3>{hospital.name}</h3><span className="context-city">{hospital.city} · General Medicine</span><div className="context-grid"><div><b>{ahead}</b><span>patients ahead</span></div><div><b>{wait} min</b><span>estimated wait</span></div><div><b>{availability?.doctors_available || '—'}</b><span>doctors available</span></div><div><b>{availability?.next_slot || '—'}</b><span>next checkup slot</span></div></div><div className="prototype-note"><ShieldCheck size={16} /><span>QureAI provides prototype queue information only. It does not diagnose conditions or replace a clinician.</span></div></div></div></div>
}

function NotificationPage({ ahead, wait, navigate, notifications, setNotifications }) { const approaching = ahead <= 3; return <div className="page-container inner-page"><PageHeader eyebrow="PATIENT UPDATES" title="Your notifications" description="Quiet, useful updates that help you decide when to head back to the OPD." action={<button className={`toggle ${notifications ? 'on' : ''}`} onClick={() => setNotifications(!notifications)}><span />{notifications ? 'Notifications on' : 'Notifications off'}</button>} /><div className="notification-layout"><div className="notification-panel"><div className="notification-panel-head"><span className="notification-bell"><BellRing size={21} /></span><div><span className="eyebrow">SMART ALERT</span><h2>{approaching ? 'Your turn is approaching!' : 'You’re on the list.'}</h2></div><span className="notification-time">Now</span></div><p>Only <b>{Math.max(3, ahead)} patients</b> are ahead of you in the General Medicine queue.</p><div className="alert-estimate"><span>Estimated waiting time</span><strong>{approaching ? '8–12' : `${Math.max(8, wait - 3)}–${wait + 4}`} <small>minutes</small></strong></div><div className="notification-actions"><Button onClick={() => navigate('queue')} icon={Activity}>View queue</Button><Button onClick={() => {}} variant="secondary" icon={X}>Dismiss</Button></div></div><div className="notification-side"><div className="eyebrow">UPDATES YOU’LL RECEIVE</div><div className="update-preference"><div className="preference-icon"><Clock3 size={17} /></div><div><b>Turn approaching</b><span>When 3 patients are ahead</span></div><Check size={17} className="preference-check" /></div><div className="update-preference"><div className="preference-icon"><MessageCircle size={17} /></div><div><b>Queue movement</b><span>When the current token changes</span></div><Check size={17} className="preference-check" /></div><div className="notification-footnote"><Bell size={15} /> Notifications are simulated for this demo.</div></div></div></div> }

function AdminPage({ queue, ahead, wait, moveQueue, setQueue }) { const rows = baseQueue.slice(0, 4).map((item, index) => index === 0 ? { ...item, token: formatToken(queue.current) } : item); return <div className="page-container inner-page"><PageHeader eyebrow="STAFF WORKSPACE" title="Good morning, Dr. Sharma." description="A focused view of the General Medicine OPD queue at CityCare." action={<span className="staff-chip"><Stethoscope size={15} /> Staff mode</span>} /><div className="stats-grid"><StatCard icon={Users} label="Patients waiting" value={ahead} detail="In current queue" /><StatCard icon={Check} label="Completed today" value="36" detail="+8 from yesterday" color="mint" /><StatCard icon={Activity} label="Current token" value={formatToken(queue.current)} detail="Consulting now" color="lavender" /><StatCard icon={Clock3} label="Avg. consultation" value="4.2 min" detail="Last 10 patients" color="peach" /></div><div className="admin-toolbar"><div><h2>Queue control</h2><p>Manage patient flow in real time.</p></div><div className="toolbar-actions"><Button onClick={() => moveQueue(1)} icon={Zap}>Call next</Button><Button onClick={() => setQueue({ ...queue, paused: !queue.paused })} variant="secondary" icon={queue.paused ? Play : Pause}>{queue.paused ? 'Resume queue' : 'Pause queue'}</Button></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Token</th><th>Patient</th><th>Status</th><th>Waiting time</th><th>Action</th></tr></thead><tbody>{rows.map((item, index) => <tr key={item.token}><td><b>{item.token}</b>{index === 0 && <span className="now-pill">NOW</span>}</td><td>{item.patient}</td><td><span className={`table-status ${index === 0 ? 'consulting' : ''}`}><span />{index === 0 ? 'Consulting' : 'Waiting'}</span></td><td>{index === 0 ? '—' : item.wait}</td><td><button className="table-action" onClick={() => moveQueue(1)}>{index === 0 ? 'Complete' : 'Call'} <ChevronRight size={14} /></button></td></tr>)}</tbody></table></div><div className="admin-disclaimer"><ShieldCheck size={15} /> Demo workspace · Actions update the shared simulated queue for patient views.</div></div> }

function AnalyticsPage() { const bars = [24, 42, 58, 72, 88, 76, 62, 46, 36, 28]; return <div className="page-container inner-page"><PageHeader eyebrow="OPERATIONS INSIGHT" title="Analytics that help teams improve." description="A snapshot of today’s OPD performance, powered by demo data." action={<span className="date-chip"><CalendarDays size={15} /> Today · 19 Sep 2026</span>} /><div className="stats-grid analytics-stats"><StatCard icon={Check} label="Patients served today" value="36" detail="Across 4 departments" color="mint" /><StatCard icon={Clock3} label="Average waiting time" value="27 min" detail="↓ 12% from last week" /><StatCard icon={Stethoscope} label="Average consultation" value="4.2 min" detail="Stable this week" color="lavender" /><StatCard icon={TrendingUp} label="Peak OPD time" value="10–12" detail="Most active window" color="peach" /></div><div className="analytics-grid"><div className="analytics-card wide"><div className="card-title"><div><div className="eyebrow">PATIENT FLOW</div><h2>Patients served per hour</h2></div><span className="chart-legend"><i /> Patients served</span></div><div className="bar-chart">{bars.map((height, index) => <div className="bar-col" key={index}><span style={{ height: `${height}%` }} /><small>{index + 8}:00</small></div>)}</div></div><div className="analytics-card"><div className="card-title"><div><div className="eyebrow">WAITING TIME</div><h3>Average waiting time</h3></div><span className="trend-up">↓ 12%</span></div><div className="big-analytic">27 <small>min</small></div><div className="sparkline"><MiniChart /></div></div><div className="analytics-card"><div className="card-title"><div><div className="eyebrow">CONSULTATION</div><h3>Duration pattern</h3></div><Clock3 size={18} /></div><div className="duration-list"><div><span>Under 4 min</span><b>42%</b><i><em style={{ width: '42%' }} /></i></div><div><span>4–6 min</span><b>38%</b><i><em style={{ width: '38%' }} /></i></div><div><span>Over 6 min</span><b>20%</b><i><em style={{ width: '20%' }} /></i></div></div></div><div className="analytics-card wide"><div className="card-title"><div><div className="eyebrow">QUEUE SIZE</div><h2>Queue size throughout the day</h2></div><span className="chart-legend"><i className="purple-dot" /> Queue size</span></div><div className="queue-spark"><MiniChart /></div></div></div><div className="prototype-note analytics-note"><ShieldCheck size={16} /><span>Analytics shown here use realistic mock data for the hackathon prototype.</span></div></div> }
